import { useEffect, useState } from "react";
import { ArrowLeft, CalendarDays, Clock3, CreditCard, MapPin, Users } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { requestJson } from "../../lib/authApi.js";
import { demoCustomer, demoSessionKey } from "../../data/demoCustomer.js";
import { ProfileFrame } from "./CustomerReservationsPage.jsx";
import "./CustomerProfilePage.css";

const dateText = (value) => value ? new Intl.DateTimeFormat("en-IN", { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(new Date(`${value}T12:00:00`)) : "—";
const timeText = (value) => { if (!value) return "—"; const [h, m] = value.split(":").map(Number); return `${h % 12 || 12}:${String(m).padStart(2, "0")} ${h >= 12 ? "PM" : "AM"}`; };
const title = (value) => (value || "").replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());

export default function CustomerReservationDetailsPage() {
  const { reservationId } = useParams(); const navigate = useNavigate(); const [user, setUser] = useState(null); const [reservation, setReservation] = useState(null); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { try { setError(""); setReservation(await requestJson(`/api/customer/reservations/${reservationId}`)); } catch (reason) { setError(reason.message); } }
  useEffect(() => { let alive = true; const demo = import.meta.env.DEV && sessionStorage.getItem(demoSessionKey) === "active"; (demo ? Promise.resolve(demoCustomer) : requestJson("/api/customer/me")).then((value) => alive && setUser(value)).catch(() => alive && navigate("/customer/login", { replace: true })); load(); return () => { alive = false; }; }, [reservationId, navigate]);
  async function cancel() { if (!window.confirm("Cancel this reservation?")) return; setBusy(true); setNotice(""); try { await requestJson(`/api/customer/reservations/${reservationId}/cancel`, { method: "POST" }); setNotice("Reservation cancelled."); await load(); } catch (reason) { setNotice(reason.message); } finally { setBusy(false); } }
  return <ProfileFrame user={user}><section className="profile-card reservation-detail-card"><Link className="reservation-back" to="/customer/profile/reservations"><ArrowLeft size={16} /> Back to reservations</Link>{error ? <p className="profile-empty">{error}</p> : !reservation ? <p className="profile-empty">Loading reservation…</p> : <><div className="reservation-detail-heading"><div><span className="reservation-kicker">RESERVATION DETAILS</span><h1>{reservation.restaurant_name || "Restaurant reservation"}</h1><p>{reservation.restaurant_location || ""}</p></div><span className={`reservation-status ${reservation.status?.toLowerCase()}`}>{title(reservation.status)}</span></div>{notice && <p className="reservation-notice">{notice}</p>}<div className="reservation-detail-grid"><div><CalendarDays /><span>Date</span><strong>{dateText(reservation.reservation_date)}</strong></div><div><Clock3 /><span>Time</span><strong>{timeText(reservation.start_time)} – {timeText(reservation.end_time)}</strong></div><div><Users /><span>Party size</span><strong>{reservation.number_of_guests} guests</strong></div><div><MapPin /><span>Table</span><strong>{reservation.tables?.length ? reservation.tables.map((table) => `${table.floor_name} · Table ${table.table_number}`).join(", ") : "Not assigned"}</strong></div><div><CreditCard /><span>Reservation fee</span><strong>₹{Number(reservation.fee_amount || 0).toFixed(2)} · {title(reservation.payment_status)}</strong></div><div><span className="reservation-detail-ref">#</span><span>Reservation ID</span><strong>{reservation.id.slice(0, 8).toUpperCase()}</strong></div></div>{reservation.fulfillment_type === "PREORDER" && <div className="reservation-special"><span>Preordered food · Pay at desk</span><p>{(reservation.preorder_items || []).map((item) => <span className="preorder-detail-line" key={item.variant_id}>{item.quantity} × {item.food_name} · {item.variant_name} — ₹{Number(item.line_total).toFixed(2)}<br /></span>)}Food subtotal ₹{Number(reservation.preorder_total || 0).toFixed(2)}</p></div>}{reservation.special_request && <div className="reservation-special"><span>Special request</span><p>{reservation.special_request}</p></div>}<div className="reservation-detail-actions"><Link to={`/customer/restaurants/${reservation.restaurant_id}`}>View restaurant</Link>{["PENDING_PAYMENT", "CONFIRMED"].includes(reservation.status) && <button disabled={busy} onClick={cancel}>{busy ? "Cancelling…" : "Cancel reservation"}</button>}</div></>}</section></ProfileFrame>;
}
